config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles
  # get 'pages/home', to: 'pages#home'
  # get 'pages/about', to: 'pages#about' #would be links like 3000/pages/about
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:edit, :update, :show, :destroy]

    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def edit
        set_article#@article = Article.find(params[:id])
    end

    def update
        set_article # @article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:notice] = "Updated!"
            redirect_to article_path(@article)
        else
            render "edit"
        end
    end

    def create
         @article = Article.new(article_params)
        if @article.save
            flash[:notice] = "Success!"
            redirect_to article_path(@article)
        else 
            render 'new'
        end
        # @article.save
        # redirect_to article_path(@article)
    end

    def show
        set_article # @article = Article.find(params[:id])
    end

    def destroy
        set_article #@article = Article.find(params[:id])
        @article.destroy
        flash[:notice] = "Article deleted"
        redirect_to articles_path
    end

    private
    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2 id="error"> The following errors prevented the article from being created: </h2>
<ul>
    <% @article.errors.full_messages.each do |msg|%>
          <li><%= msg %></li>
  <% end%>
<ul>
<% end %>

<%= form_for @article do |f| %>

    <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
    </p>

    <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>
    </p>

    <p>
    <%= f.submit %>
    </p>
<% end %>

<%= link_to "<< Articles", articles_path%>

app/views/articles/edit.html.erb
<h1> Edit article</h1>

<% if @article.errors.any? %>
<h2 id="error"> The following errors prevented the article from being created: </h2>
<ul>
    <% @article.errors.full_messages.each do |msg|%>
          <li><%= msg %></li>
  <% end%>
<ul>
<% end %>

<%= form_for @article do |f| %>
    <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
    </p>

    <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>
    </p>

    <p>
    <%= f.submit %>
    </p>
<% end %>
<%= link_to "<< Articles", articles_path%>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>
<br> <%= link_to "Create new article", new_article_path%>

<table>
    <tr>
        <th>Title</th>
        <th>Description</th>
    </tr>

    <% @articles.each do |article|%>
    <tr>
        <td> <%= article.title %> </td>
        <td> <%= article.description %> </td>
        <td> <%= link_to 'Edit', edit_article_path(article)%> </td>
        <td> <%= link_to 'Show', article_path(article)%> </td>
        <td> <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "You for real?"} %> </td>
    </tr>
    <% end %>
</table>
<%= link_to 'Home', root_path %>

app/views/articles/new.html.erb
<h1> Create an article </h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Your recent article</h1>

<p id= "article_submission"> 
    Title: <%= @article.title %>
</p>

<p id= "article_submission"> 
    Description: <%= @article.description %>
</p>
<%= link_to "<< Articles", articles_path%>
<%= link_to "Edit", edit_article_path(@article)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |name, msg|%>
      <ul>
        <li> <%= msg %> </li>
      </ul>
  <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<!-- <h1>I worked: About -->
<%# <%= link_to 'Home', root_path %>

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="/stylesheets/application.css">
        <title>About Me</title>
    </head>
    <body>
        <h1>About Me</h1>
          <ul id="links">
            <%# <li><a href="home.html">Home</a></li> %>
            <%= link_to 'Home', root_path %> 
            <%= link_to 'About', about_path%>
            <%= link_to "Blog", articles_path%>
            <%# <li><a href="about.html">About</a></li> %>
            <%# <li><a href="mailto:lovemercybiz@gmail.com">Contact</a></li> %>
        </ul>
    </body>
</html>

app/views/pages/home.html.erb
<%# <!-- <%= link_to 'About', welcome_about_path
<%# <h1> I worked: Home %>
<%# <%= link_to 'About', pages_about_path %>
<%# <!-- erb ^^^ -->  %>
<%# <%= link_to 'About', welcome_about_path%> 

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="/stylesheets/application.css">
        <title>Home</title>
    </head>
    <body>
        <h1>Alpha Blog</h1>
        <ul id="links">
             <%= link_to 'Home', root_path %>

            <%= link_to 'About', about_path%>

            <%= link_to "Blog", articles_path%>
            <%# <li><a href="mailto:lovemercybiz@gmail.com">Contact</a></li> %>
        </ul>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Amet debitis autem cumque reiciendis sed quidem labore numquam, alias obcaecati voluptatum vel deleniti distinctio laboriosam dolores, similique aperiam vitae laudantium? Consequatur Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem exercitationem iure cumque laboriosam? Consequuntur earum sunt repellendus, accusantium sint praesentium fugiat doloremque asperiores aperiam itaque deleniti eaque omnis natus reprehenderit?</p>
        <!-- <img src="/AlphaBlog/app/assets/images/321298.jpg" alt="motivation"> --><!-- not working -->
    </body>
</html>